name: Create Directory and Clone Repository on Azure VM

on:
  workflow_dispatch: # Enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Set Up SSH using the private key (for SSH host verification)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      - name: Debug environment variables
        run: |
          echo "Password is: ${{ secrets.AZURE_VM_PASSWORD }}"
          echo "Username: ${{ secrets.AZURE_VM_USERNAME }}"
          echo "IP: ${{ secrets.AZURE_VM_IP }}"

      - name: Create Directory and Clone Repository
        env:
          SSH_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 2022 -o StrictHostKeyChecking=no -T ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          mkdir -p ~/hayden
          cd ~/hayden
          git clone https://github.com/Haydenpal/Microservices.git
          EOF
