name: Create Directory on Azure VM

on:
  push:
    branches:
      - Development-Testing
  workflow_dispatch: # Enable manual trigger

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      # Step 1: Set up SSH using the private key (for SSH host verification)
      - name: Set Up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key

      # Step 2: Log in and create a new directory using password-based authentication
      - name: Create Directory on Azure VM using Password
        env:
          SSH_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}  # Provide password as a secret
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -p 2022 -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          mkdir -p ~/hayden  # Creates a directory named 'hayden' in the user's home directory
          EOF
